name: cpp-linter
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Sources/CSFBAudioEngine/**/*.h'
      - 'Sources/CSFBAudioEngine/**/*.hpp'
      - 'Sources/CSFBAudioEngine/**/*.c'
      - 'Sources/CSFBAudioEngine/**/*.cpp'
      - 'Sources/CSFBAudioEngine/**/*.m'
      - 'Sources/CSFBAudioEngine/**/*.mm'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'Sources/CSFBAudioEngine/**/*.h'
      - 'Sources/CSFBAudioEngine/**/*.hpp'
      - 'Sources/CSFBAudioEngine/**/*.c'
      - 'Sources/CSFBAudioEngine/**/*.cpp'
      - 'Sources/CSFBAudioEngine/**/*.m'
      - 'Sources/CSFBAudioEngine/**/*.mm'
permissions:
  contents: read
  pull-requests: write
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: '-*'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          format-review: true
          extensions: 'h,hpp,c,cpp,m,mm'
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
